language: python
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      python: 2.7
      cache: pip
      env: TOXENV=py27
    - os: osx
      language: generic
      cache: pip
      env: TOXENV=py27
    - os: linux
      python: 3.6
      cache: pip
      env: TOXENV=py36
    - os: osx
      cache: pip
      language: generic
      env: TOXENV=py36
addons:
  apt:
    packages:
      - python-imdbpy
      - python-notify2
install:
  - pip install -r requirements.txt
script:
  - cd $TRAVIS_BUILD_DIR/
  - flake8 --select E,W --max-line-length=140 --ignore E722 jarviscli/
  - cd jarviscli/
  - python -m unittest discover
