
language: python
matrix:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py27
addons:
  apt:
    packages:
      - python-dbus-dev python-dbus libdbus-1-dev libdbus-glib-1-dev
      - python-imdbpy python-notify2 libssl-dev libffi-dev
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - cd $TRAVIS_BUILD_DIR/
  - flake8 --select E,W --max-line-length=140 --ignore E722 jarviscli/
  - cd jarviscli/
  - coverage run -m unittest discover
after_success:
  - codecov
