dist: trusty
language: python
python:
  - "2.7"

install:
  - sudo apt-get install python3 python-dbus-dev python-dbus libdbus-1-dev libdbus-glib-1-dev
  - pip install dbus-python
  - cd $TRAVIS_BUILD_DIR
  - ./setup.sh

script:
  - pip install -r requirements.txt
  - cd jarviscli/
  - python -m unittest discover
